short_name = "Nightmare"
name = "Nightmare Engine"
major = 4
minor = 3
patch = 0
status = "alpha"
status_version = 2
module_config = ""
website = "https://redotengine.org"
docs = "latest"
godot_major = 4
godot_minor = 4
godot_patch = 0
godot_status = "dev"
